query ReadmeData($keyValuePairs: [String], $setOfProjectsCollectionId: String, $projectsLimit: Int) {
    keyValuePairCollection(where: {
        key_in: $keyValuePairs
    }) {
        items {
            key,
            value
        }
    },
    setOfProjectsCollection(where: {
        id: $setOfProjectsCollectionId
    }, limit: 1) {
        items {
            featuredProjectsCollection(limit: $projectsLimit) {
                items {
                    ...FeaturedProject
                }
            }
        }
    }
    positionCollection {
        items {
            ...PositionReadme
        }
    }
}

fragment FeaturedProject on Project {
    title,
    url,
    codeUrl,
    tagline,
    mediaCollection(limit: 1) {
        items {
            ...ProjectMedia
        }
    }
}

fragment ProjectMedia on Asset {
    title,
    width,
    height,
    url(transform: {
        format: WEBP,
        height: 400,
        quality: 50
    })
}

fragment PositionReadme on Position {
    company,
    companyUrl,
    position,
    startDate
}